"""initial schema

Revision ID: 01d7438288bc
Revises: 
Create Date: 2026-08-12 00:49:42.436236
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '01d7438288bc'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Trigram matching for fuzzy course/major lookups. Course codes arrive from
    # multiple registrar exports with inconsistent formatting ("BIO 101" vs
    # "BIO-101"), and pg_trgm lets those resolve in SQL rather than in Python.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumni',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=False),
    sa.Column('outcome_title', sa.String(length=160), nullable=False),
    sa.Column('outcome_org', sa.String(length=160), nullable=False),
    sa.Column('career_area', sa.String(length=128), nullable=False),
    sa.Column('interests', sa.ARRAY(sa.String(length=128)), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alumni_career_area'), 'alumni', ['career_area'], unique=False)
    op.create_index(op.f('ix_alumni_graduation_year'), 'alumni', ['graduation_year'], unique=False)
    op.create_table('precompute_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('student_id', sa.String(length=64), nullable=True),
    sa.Column('alumni_scored', sa.Integer(), nullable=False),
    sa.Column('clusters_built', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_precompute_runs_created_at'), 'precompute_runs', ['created_at'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('year', sa.Enum('freshman', 'sophomore', 'junior', 'senior', name='student_year'), nullable=False),
    sa.Column('declared_major', sa.String(length=128), nullable=True),
    sa.Column('intended_direction', sa.String(length=128), nullable=True),
    sa.Column('interests', sa.ARRAY(sa.String(length=128)), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alumnus_courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alumnus_id', sa.String(length=64), nullable=False),
    sa.Column('course_code', sa.String(length=32), nullable=False),
    sa.Column('course_name', sa.String(length=160), nullable=False),
    sa.Column('semester_index', sa.Integer(), nullable=False),
    sa.Column('dropped', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['alumnus_id'], ['alumni.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alumnus_courses_alumnus_id'), 'alumnus_courses', ['alumnus_id'], unique=False)
    op.create_index('ix_alumnus_courses_alumnus_semester', 'alumnus_courses', ['alumnus_id', 'semester_index'], unique=False)
    op.create_index(op.f('ix_alumnus_courses_course_code'), 'alumnus_courses', ['course_code'], unique=False)
    op.create_table('alumnus_majors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alumnus_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('declared_semester', sa.Integer(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['alumnus_id'], ['alumni.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alumnus_majors_alumnus_id'), 'alumnus_majors', ['alumnus_id'], unique=False)
    op.create_index(op.f('ix_alumnus_majors_name'), 'alumnus_majors', ['name'], unique=False)
    op.create_table('milestones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alumnus_id', sa.String(length=64), nullable=False),
    sa.Column('semester_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['alumnus_id'], ['alumni.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_milestones_alumnus_id'), 'milestones', ['alumnus_id'], unique=False)
    op.create_table('pivots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alumnus_id', sa.String(length=64), nullable=False),
    sa.Column('semester_index', sa.Integer(), nullable=False),
    sa.Column('from_major', sa.String(length=128), nullable=False),
    sa.Column('to_major', sa.String(length=128), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['alumnus_id'], ['alumni.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pivots_alumnus_id'), 'pivots', ['alumnus_id'], unique=False)
    op.create_table('student_courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(length=64), nullable=False),
    sa.Column('course_code', sa.String(length=32), nullable=False),
    sa.Column('course_name', sa.String(length=160), nullable=False),
    sa.Column('semester_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_student_courses_student_code', 'student_courses', ['student_id', 'course_code'], unique=True)

    op.create_index(op.f('ix_student_courses_student_id'), 'student_courses', ['student_id'], unique=False)
    # ### end Alembic commands ###

    # GIN trigram indexes backing the fuzzy lookups described above.
    op.execute(
        "CREATE INDEX ix_alumnus_courses_code_trgm "
        "ON alumnus_courses USING gin (course_code gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX ix_alumnus_majors_name_trgm "
        "ON alumnus_majors USING gin (name gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX ix_alumni_career_area_trgm "
        "ON alumni USING gin (career_area gin_trgm_ops)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_alumni_career_area_trgm")
    op.execute("DROP INDEX IF EXISTS ix_alumnus_majors_name_trgm")
    op.execute("DROP INDEX IF EXISTS ix_alumnus_courses_code_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_courses_student_id'), table_name='student_courses')
    op.drop_index('ix_student_courses_student_code', table_name='student_courses')
    op.drop_table('student_courses')
    op.drop_index(op.f('ix_pivots_alumnus_id'), table_name='pivots')
    op.drop_table('pivots')
    op.drop_index(op.f('ix_milestones_alumnus_id'), table_name='milestones')
    op.drop_table('milestones')
    op.drop_index(op.f('ix_alumnus_majors_name'), table_name='alumnus_majors')
    op.drop_index(op.f('ix_alumnus_majors_alumnus_id'), table_name='alumnus_majors')
    op.drop_table('alumnus_majors')
    op.drop_index(op.f('ix_alumnus_courses_course_code'), table_name='alumnus_courses')
    op.drop_index('ix_alumnus_courses_alumnus_semester', table_name='alumnus_courses')
    op.drop_index(op.f('ix_alumnus_courses_alumnus_id'), table_name='alumnus_courses')
    op.drop_table('alumnus_courses')
    op.drop_table('students')
    op.drop_index(op.f('ix_precompute_runs_created_at'), table_name='precompute_runs')
    op.drop_table('precompute_runs')
    op.drop_index(op.f('ix_alumni_graduation_year'), table_name='alumni')
    op.drop_index(op.f('ix_alumni_career_area'), table_name='alumni')
    op.drop_table('alumni')
    # ### end Alembic commands ###
